FROM registry.access.redhat.com/ubi9/go-toolset:1.22 AS builder
WORKDIR /opt/app-root/src
COPY go.mod .
COPY main.go .
RUN go build -o canary main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5
COPY --from=builder /opt/app-root/src/canary /usr/local/bin/canary
ENTRYPOINT ["canary"]
